# -*- MakeFile -*-

options = -Wall -Wextra -Werror -pedantic

all: todo_api_0
# todo_api_1 todo_api_2 todo_api_3 todo_api_4

todo_api_0: 4-server.c
	gcc $(options) 4-server.c helpers_src/*.c -o todo_api_0

# todo_api_1: 5-server.c
#	gcc -Wall -Wextra -Werror -pedantic 5-server.c -o todo_api_1

#todo_api_2: 6-server.c
# 	gcc -Wall -Wextra -Werror -pedantic 6-server.c -o todo_api_2

# todo_api_3: 7-server.c
# 	gcc -Wall -Wextra -Werror -pedantic 7-server.c -o todo_api_3

# todo_api_4: 8-server.c
# 	gcc -Wall -Wextra -Werror -pedantic 8-server.c -o todo_api_4
