# -*- MakeFile -*-

all: strace_0 strace_1 strace_2

strace_0: task0.c
	gcc -Wall -Wextra -Werror -pedantic task0.c -o strace_0

strace_1: task1.c
	gcc -Wall -Wextra -Werror -pedantic task1.c -o strace_1

strace_2: task2.c
	gcc -Wall -Wextra -Werror -pedantic task2.c -o strace_2

